### PR TITLE
Add breadcrumbs to uncaught exceptions

### LINKED ISSUE #114: UncaughtExceptionHandler doesn't add breadcrumbs to SentryEventBuilder
When Sentry-Android handles a runtime exception with its uncaughtExceptionHandler it doesn't appear to add any accumulated breadcrumbs to the event posted to the Sentry server, whereas manually caught exceptions posted with Sentry.captureException and Sentry.captureEvent do include breadcrumbs. 

Is there a reason why the uncaughtExceptionHandler omits breadcrumbs? It would be quite useful for determining the events leading up to a runtime crash.

Would it be possible to add this for uncaught exceptions in a future release?

I'm currently using Sentry-Android 1.5.2 in my app as this appears to be the latest I can get from jCenter.

### PR DESCRIPTION
**Pull request by marcomorain**
Fixes #114

### CODE REVIEW

**Comment by edenman** [comment]
@marcomorain i don't see 1.5.4 on jcenter...has it actually been released?  https://bintray.com/joshdholtz/maven/sentry-android

**Comment by marcomorain** [comment]
Hi @edenman - I've pinged @joshdholtz to ask him to cut a new release.

Thanks for keeping us honest!

**Comment by marcomorain** [comment]
@edenman 💥 https://twitter.com/joshdholtz/status/831985735909724160

**Comment by edenman** [comment]
🙌

**Pull request merged**
