### PR TITLE
Execute HTTP POST on a background thread

### PR DESCRIPTION
**Pull request by felipeska**
Execute HTTP POST on a background thread. AsyncTask enables proper and
easy use of the UI thread, in this case it is not necessary ;)

### CODE REVIEW

**Comment by spidfire** [comment]
Any progress on this?

**Comment by felipeska** [comment]
@spidfire  a problem or bug related to this?

**Comment by spidfire** [comment]
Nope just wondering if this will be done or not

**Comment by joshdholtz** [comment]
Hey @spidfire  and @felipeska! Sorry about losing track of this PR :pensive: Taking a look again at this right now

**Pull request closed without merging**
